name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Gitlab action job"
        - name: List files
          run: ls
        - name: Read file
          run : cat  README.md