name: Generate ASCII Framework

on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay command
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt
        - name: Test files exists
          run: grep -i "dragon" dragon.txt
        - name: Read file
          run: cat dragon.txt
        - name: List Repo files
          run: ls -ltra

